### ISSUE TITLE
Upcoming changes in biblatex 3.8

### ISSUE THREAD

**Issue by moewew** [alex-ball/biblatex-oxref#1]
`biblatex` 3.8 is hopefully going to be released quite soon.

Some of the changes in that version might be relevant to this style
- `\DeclareSortingScheme` will be called `\DeclareSortingTemplate`
- `extrayear` becomes `extradate`, macro names that make reference to `extrayear` were also changed.

Backwards compatibility code is in place to allow styles using the old name to continue to work (the old names issue warnings), but it would be appreciated if developers made the transition to the new names.

The full list of changes is at https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/CHANGES.org and https://github.com/plk/biblatex/wiki. Maybe you can make use of some of the new features.

**Comment by alex-ball** [comment]
Many thanks for bringing these changes to my attention. I will make the necessary adjustments and issue an update as soon as possible.
