### ISSUE TITLE
Weird citation style for edited works

### ISSUE THREAD

**Issue by wujastyk** [alex-ball/biblatex-oxref#10]
Using TeXlive 2019 updated to the present; oxyear.dbx 2019/09/02 v1.2; xelatex.

When I `\cite` a critical edition of a text, which has an `editor` but no `author`, I get the whole of the title written out, where I would haved expected just "Gupta 1835--6"

![image](https://user-images.githubusercontent.com/762246/64761622-bb8c7380-d4f9-11e9-88ae-0fb24e5e2b2c.png)

Here's the bib entry:

```
@Mvbook{gupt-1835,
  title       = {Susruta or System of Medicine Taught by Dhanwantari and Composed by His Disciple Suśruta},
  date        = {1835/1836},
  editor      = {Madhusudana Gupta},
  volumes     = {2},
  publisher   = {Education Press},
  location    = {Calcutta},
  owner       = {dom},
  related     = {gupt-1835,gupt-1836},
  relatedtype = {multivolume},
  timestamp   = {2019-09-11},
  volume      = {1},
}
```

**Comment by alex-ball** [comment]
This is the intended and documented behaviour: please see sections 4.1 and 4.2 of the oxyear manual for the rationale. You have three choices:

  - Go with it, and consider using `shorttitle` to abbreviate the citation label.
  - Override the behaviour for this one entry with `options={useeditor}`.
  - Switch to `@mvcollection` (which does not sound semantically correct).

I am also a bit concerned that you have specified that this book is a multivolume work, one volume of which is itself (a multivolume work, one volume of which is a multivolume work, one volume of which is...). The `multivolume` relation is intended to be used within a `@mvbook` (or `@mvcollection` or `@mvreference`) -- the entire series of volumes -- to specify the list of component `@book` (or `@collection` or `@reference`) volumes. One clue that something is not right is that you would not normally specify `volume` and `volumes` in the same entry. You should have something like this:

```
@mvbook{gupt-1835-6,
  ...
  date = {1835/1836},
  volumes = {2},
  related     = {gupt-1835,gupt-1836},
  relatedtype = {multivolume},
  ...
}
@book{gupt-1835,
  date = {1835},
  volume = {1},
  ...
}
@book{gupt-1836,
  date = {1836},
  volume = {2},
  ...
}
```

But you don't necessarily have to use that relation. There is a whole section in the oxyear manual (4.4) to help you get the effect you want for multivolume works.

**Comment by alex-ball** [comment]
Though not related to your issue, I realised in answering it that the way I handled the multivolume relation in my ritter1838hap1-3 reference was just plain wrong. The next release of oxref will remedy this, making the example at last portable between styles. So thank you for making me look at this again.

**Comment by wujastyk** [comment]
Thanks very much for this, Alex.  I have never used mv- before, so I'm just
learning the ropes for the first time on this.  I shall go and RTFM :-)  I
should have done so already.  I'm usually quite good at reading the docs.

I've now used what you said and it works as it should.  Much better. Thanks
again!
Dominik
