### ISSUE TITLE
Problem with \emph in journal field

### ISSUE THREAD

**Issue by wujastyk** [alex-ball/biblatex-oxref#13]
If I have a font-changing command like \emph or \it or \textit in the journal or journaltitle field, biblatex gives this error:

```
! Use of \\blx@imc@printtext doesn't match its definition.
\text@command #1->\def \reserved@a {
                                    #1}\ifx \reserved@a \@empty \let \check@...
l.48 \end
         {document}
If you say, e.g., `\def\a1{...}', then you must always
put `1' after `\a', since control sequence names are
made up of letters only. The macro here has not been
followed by the required stuff, so I'm ignoring it.
```
I'm attaching a MWE

[bibtest.zip](https://github.com/alex-ball/biblatex-oxref/files/5761248/bibtest.zip)

**Comment by alex-ball** [comment]
I've narrowed this down to the `\ifabbrev` macro that oxref defines, which uses the xstring macro `\StrRight`. Something about biblatex breaks this macro:

```latex
\documentclass{article}
\usepackage{biblatex}
\usepackage{xstring}
\begin{document}
\StrRight{ABC\emph{x}yz}{1}[\mytemp] \mytemp
\end{document}
```

This throws an error. The error goes away if biblatex is not loaded or the test string has no `\emph`.

I will have to do some investigating to track down what is going wrong.

**Comment by alex-ball** [comment]
I am still not sure what biblatex is doing to break xstring, but I think this may solve your immediate issue.

After loading biblatex with an oxref style, add this fix:

```latex
\makeatletter
\renewcommand*{\ifabbrev}[3]{%
  \bgroup\normalexpandarg
  \StrRight{#1}{1}[\blx@ox@lastchar]%
  \IfSubStr{\blx@ox@abbrevstring}{\blx@ox@lastchar}{#2}{#3}%
  \egroup
}
\makeatother
```

The `\normalexpandarg` context seems to stop whatever weird expansion behaviour is triggering the error. I will need to do more testing before I push the change out in a new release, though.

**Comment by wujastyk** [comment]
The new \ifabbrev definition fixes the error in my test file, but not in the larger real file that I'm working on. 
 I am using a slightly messy set of biblatex options and customizations, so there may be another interaction that's local to me.  I don't ask you to debug my biblatex style file, but it's hssa-biblatex.sty at [https://github.com/wujastyk/HSSA](https://github.com/wujastyk/HSSA) in case you wanted to look at it and something jumps out.  You don't have to look at it!

**Comment by alex-ball** [comment]
I have just compiled your template_HSSA.tex (commenting out images, fonts, etc. that I didn't have) with your bibtest.bib file and the fix worked fine. I added it directly after the `\usepackage[...]{biblatex}` lines (around l.44) in hssa-biblatex.sty, but without the `\makeatletter` and `\makeatother` lines as it's a package file.

I would really appreciate it if you could isolate the error you are still experiencing and the entries that trigger it. You may have found a different bug, or there may be some additional corner cases in xstring that `\normalexpandarg` doesn't fix.

**Comment by wujastyk** [comment]
Thank you so much for taking the trouble, Alex.  I will try to get a MWE
for you, but it may take a few days.

**Comment by alex-ball** [comment]
Upon further investigation, it turns out the above fix is functionally equivalent to this:

```latex
\renewcommand*{\ifabbrev}[3]{#3}
```

which will definitely work in all cases for you and defeat a design goal for me.

What I was intending to do with the expansion context was sanitise the string that xstring was working with – alas, the expansion does not stop at the right point for this purpose – but what I should have remembered is that biblatex has its own mechanism for that. So the approach I'm now taking is to feed the function `\strfield{...}` instead of `\thefield{...}`. This necessitates a bit of finessing to get around the mismatched catcodes, as you'll see in the commit.

I've tested these changes in your HSSA context and I don't get any errors. The next step will be to see if the new code still triggers errors in your real-world document.

**Comment by wujastyk** [comment]
The \renewcommand worked a treat.

Thank you so much.  Sorry about your design goal.  Macro expansion timing
is the devil.

Warm regards,
Dominik

**Comment by alex-ball** [comment]
The design goal in question is to suppress punctuation after the journal title if it is abbreviated, so `\ifabbrev` is testing to see if it ends in a capital letter or dot. It's not a perfect way of detecting abbreviations but it works well enough in most cases.

I am fairly confident that the changes I committed in 96d430f should satisfy us both. In the longer term I may have to look at replacing all the xstring operations with LaTeX3 ones.

**Comment by wujastyk** [comment]
Many thanks, Alex!
