### ISSUE TITLE
Page references produced by backref option don't appear at end whe  there is a related entry

### ISSUE THREAD

**Issue by ciandorr** [alex-ball/biblatex-oxref#14]
I find biblatex's backref option quite useful as an easy substitute for an index.  But when using oxyear (and I guess the other oxref styles), the page references for entries with related entries generally appear before the related entry, which is not really desirable or sensible.  For example, I have the following `serialarticle` entry:

@article{PoincareML,
	author = {Henri Poincar{\'e}},
	date = {1905/1906},
	journaltitle = {R{\'e}vue de Metaphysique et de Morale},
	language = {french},
	pages = {815-835},
	related = {PoincareML2},
	relatedtype = {serialarticle},
	title = {Les mathematiques et la logique},
	volume = {13}}

@article{PoincareML2,
	author = {Henri Poincar{\'e}},
	language = {french},
	pages = {17-34, 294-317},
	title = {Les mathematiques et la logique},
	volume = {14}}

What appears in the bibliography with backref enabled is the following:

Poincaré, Henri (1905–6). ‘Les mathematiques et la logique’, Révue de Metaphysique et de Morale 13: 815–35 [21], 14: 17–34, 294–317.

Here the [21] is the backref citation to the page in my book where I'm citing Poincaré.  But I don't think anyone would understand this.  

I think it would make more sense to have the backrefs ALWAYS appear as the final thing in a bibliography entry, a after any related string, note, etc.  

I considered trying to implement this myself using xpatchbibdriver but the syntax for this is a bit daunting, so I thought I'd start by adding it as an issue here.  Thanks for your work on this package which has been truly invaluable to me!

**Comment by alex-ball** [comment]
Support for back references has been sort of accidental up till now, but I will look at supporting this feature properly for the next release.

I hope it will be as simple as swapping the order of the following two blocks at the end of every bib driver, but we'll see:

```latex
% needs to be second
\setunit{\bibpagerefpunct}\newblock
\usebibmacro{pageref}%
% needs to be first
\setunit{\relatedtypepunct}\newblock
\iftoggle{bbx:related}
  {\usebibmacro{related:init}%
    \usebibmacro{related}}
  {}%
```

**Comment by ciandorr** [comment]
Great, thanks!  That should make the feature much more usable.
