### ISSUE TITLE
oxyear generates an error when combined with giveninits=false

### ISSUE THREAD

**Issue by ciandorr** [alex-ball/biblatex-oxref#2]
I'd like a variant of the Oxford style where full names rather than initials are printed.  But if start a file with \usepackage[style=oxyear, giveninits=false], and cite one thing, I get an error telling me that the command \bibnamedelimd is undefined.  I can't figure out what could be causing this, \bibnamedelimd is defined in the main text of the document so something must be undefining it during \printbibliography.

**Comment by ciandorr** [comment]
I just updated to 0.11 - it's still not working but now I get a different error message, it's now saying that the undefined control sequence is \ifdefvoid.

**Comment by alex-ball** [comment]
Thank you for reporting this issue. I am able to reproduce it and am investigating. I will try to get a fix released in the next few days.

**Comment by alex-ball** [comment]
Until the new version hits CTAN, you could probably work around the issue by adding this after loading the style:

```tex
\xpatchnameformat{family-given}{%
  {\namepartgiven}%
}{%
  {\namepartgiven}{\namepartprefix}%
}{}{}
```
Remember to remove it again after upgrading!

**Comment by ciandorr** [comment]
Thanks - impressively quick turnaround!
