### ISSUE TITLE
Spanish string translations to complete

### ISSUE THREAD

**Issue by bruno-maltras** [alex-ball/biblatex-oxref#20]
Some Spanish strings seem to be lost. I could help with that.

Thanks

**Comment by alex-ball** [comment]
Many, many thanks for your help with this.

Please see [`oxref.dtx` in the `spanish` branch](https://github.com/alex-ball/biblatex-oxref/blob/spanish/oxref.dtx). Around line 15477 you should see:

```latex
% \section{Spanish: spanish-oxref.lbx}
```

The first few sections (lines 15495-15671) are the most important, as they contain the non-standard bibliography strings that oxref supports. The remaining sections are overrides for the standard bibliography strings, so if any of them are unnecessary or inappropriate you can simply remove them.

If you're not familiar with the format here, each entry is written like this:

```latex
term-identifier = {{unabbreviated form}{abbreviated form}},
```

(This supports biblatex's `abbreviate` option; if the term should always be abbreviated or unabbreviated, give the same form twice.) Abbreviation dots are added with `\adddot`; if there should always be a space afterwards, use `\adddotspace`. Full details are in section 4.9.1 ‘Localization Commands’ of the [biblatex manual](http://mirrors.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf).

**Comment by bruno-maltras** [comment]
Just commited translated strings; Only "holder" and "held by" are still pending, I have not been able to find a source for context.

**Comment by alex-ball** [comment]
Fantastic! Please open a pull request when you're ready.

The "holder/holders" roles and "byholder" action relate to patents. There is an example in `oxref.bib` with ID `arduengo.etal2001pmi` (U.S. patent 6177575, held by E. I. DuPont).

**Comment by bruno-maltras** [comment]
I finished the translation into Spanish on March, 24th, and then open a
pull request. Something went wrong, because it had no effect and I cannot
find it now. Before I retry it: in the orref.dtx file two syntax for
accented chars are used (ie Tex: \'i and laTex: \'{i} ). Both where there
before I started, and I have use mainly the first one for the new
translated strings. If one is preferable to the other, please tell me to
unify it. Could affect the syntax to the bug caused by "\.{I}" ?

**Comment by alex-ball** [comment]
Many thanks for your efforts; sorry to hear GitHub is making more work for you.

The accent commands take the next token as an argument, so `\'a` is equivalent to `\'{a}`; the difference is human readability. Looking at upstream biblatex, I think the `\'a` form is used the majority of the time. The version with the braces tends only to be used where strictly necessary, that is, where the accent command is a letter (e.g. `\c{c}`). It is unfortunate that the upstream `spanish.lbx` has more variety in it than most: it seems to have been left in a provisional or tentative state.

The specific problem with `\.` was the convoluted code needed to make LaTeX read `\...` as a separate command instead of `\.{.}.`.

**Comment by bruno-maltras** [comment]
Finally, the pull request is open. I took the chance to change the brackets syntax to the "plain" one. I hope everything is ok.
Thank you very much for your help and explanations, and of course for your work in the style (my favourite).

**Comment by alex-ball** [comment]
Upstream has added strings for some more languages. Please could you check the following full and abbreviated forms to see if they are appropriate?

```latex
  langbasque       = {{vasco}{vasc\adddot}},
  langlatvian      = {{let\'on}{let\adddot}},
  langlithuanian   = {{lituano}{lit\adddot}},
  langmarathi      = {{marathi}{mar\adddot}},
  langturkish      = {{turco}{turco}},
```
