### ISSUE TITLE
missing command in makefile?

### ISSUE THREAD

**Issue by ghost** [alex-ball/biblatex-oxref#5]
Hello! I admire your work you did with this style especially how you created the `dtx` (I studied it extensively).
However I was wondering whether there is a `cp` missing in the makefile: 
https://github.com/alex-ball/biblatex-oxref/blob/83eaa7fc1ae698274cdab77825713f8068ebcb78/Makefile#L55-L56

furthermore a `sudo` for `mktexlsr` is also needed (at least with my system; MacTeX).

Thanks.

**Comment by alex-ball** [comment]
Good catch, thank you for spotting.
