### ISSUE TITLE
Next version of biblatex will very likely drop xstring

### ISSUE THREAD

**Issue by moewew** [alex-ball/biblatex-oxref#6]
For the upcoming version we are currently planning on getting rid of `xstring` code in `biblatex`. As a consequence `biblatex` would not require `xstring` any more and would not load the `xstring` package itself any more. `biblatex` styles that need `xstring` would have to load the package explicitly themselves. See https://github.com/plk/biblatex/pull/816 for the current state of affairs.

Your style uses some `xstring` commands, for example in

https://github.com/alex-ball/biblatex-oxref/blob/af2b14aeb28551100ee3da506b6dea1c0b92fe5c/oxref.dtx#L7345

To continue working properly, the files that use those commands should load `xstring` explicitly.

Even if it turns out that the change can not go through as planned, it is still a very good idea to load `xstring` explicitly if your style needs it.

We are hoping to release a new version of `biblatex` in the not too distant future (I can't promise any ETA as of now, there will be a pre-release announcement on [comp.text.tex](https://groups.google.com/forum/#!forum/comp.text.tex)). You can learn more about the upcoming changes in https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/CHANGES.md. If you can find time to test your style against the new dev version (https://sourceforge.net/projects/biblatex/files/development/, you'll also need Biber 2.12 from https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/development/binaries/) feedback would be appreciated.

See also https://github.com/alex-ball/bathbib/issues/2

**Comment by moewew** [comment]
Oh, when I wrote this ticket I forgot that your style loads `xstring` explicitly already. So I guess I should close this ticket.

Of course the warning about the new release still stands, but we hope that there are no complications for contributed styles.

**Comment by alex-ball** [comment]
Thanks for letting me know.
