### ISSUE TITLE
british-oxref incorrect inheritence

### ISSUE THREAD

**Issue by AndrewSwann** [alex-ball/biblatex-oxref#7]
Line 36 of `british-oxref.lbx` has

      inherit          = {english-oxref},

as the first part of `\DeclareBibliographyStrings`.  This results in the warning

```
Package biblatex Warning: File 'english-oxref-oxref.lbx' not found!
(biblatex)                Ignoring mapping 'english-oxref' -> 'english-oxref-oxref'.
```

Replacing the line by just

      inherit          = {english},

removes the warning.

**Comment by alex-ball** [comment]
Thanks for your interest in improving oxref.

This change, along with others, was applied back in commit 5615cba, and will be apparent in the imminently forthcoming release.

**Comment by AndrewSwann** [comment]
Perfect - good to see a couple of other warnings dealt with too.
